### ISSUE TITLE
Better Sources for Charts, Search and Torrents

### ISSUE THREAD

**Issue by funkyg** [funkyg/funkytunes#1]
Atm they are not great, many albums cant be played. Need to find better alternatives.

**Comment by heyakyra** [comment]
Is https://musicbrainz.org/ the current source?

**Comment by funkyg** [comment]
description is in the readme: https://github.com/funkyg/funkytunes#how-does-it-work

Afaik musicbrainz doesnt have any charts or overall search (searching artist, album, song at the same time).

**Comment by gjedeer** [comment]
http://api.musicgraph.com/api/v2/album/suggest?api_key=cb9e5e892aa76c63245f049f8642c2d8&prefix=hot may be another source for charts

**Comment by funkyg** [comment]
Like we said in #11, we can use the pirate bay top100 albums: https://thepiratebay.org/top/101. and then use discogs search to get artist, album name, cover etc.

Or we could try to find a torrent site with better metadata. But i couldnt find any good site right now.

**Comment by gjedeer** [comment]
This looks awesome but their home page is just latest releases, not most popular http://music-torrent.net/

**Comment by funkyg** [comment]
yeah that site doesnt look great. i though we could use that and have a genre selection, but they have stuff like radiohead listed under hip hop

one more thing, discogs has a rate limit (60 requests per minute and ip). if we search for every single album on discogs, a fast scroll through the list might cause us to be rate limited https://www.discogs.com/developers/

**Comment by heyakyra** [comment]
strike search was the most beautiful trackerless torrent search engine ever

https://web.archive.org/web/20160204020104/http://blog.getstrike.net/post/138192622233/were-moving-away-from-torrents-so-whats-next
https://web.archive.org/web/20160204020224/https://github.com/StrikeOrg/strike-search
https://github.com/jakop345/strike-search

**Comment by gjedeer** [comment]
Hey @funkyg, long time no see. I have just implemented a SkyTorrents.in adapter in https://github.com/gjedeer/funkytunes/tree/skytorrents

Right now it's just used instead of PirateBayAdapter because that was the easier thing to do. Also the code is shit, common parts can be refactored etc. - but that's not the point now.

Good parts:
- Finds much more albums
- HTTP torrent links are present -> no wait for magnets
- Scans first 5 search results - downloads .torrent files and checks if any MP3s are present
- I could finally listen to some of the music I know, not just the itunes hits

Bad parts:
- skytorrents is a DHT crawler so the results are of varying quality
- libtorrent crashes on some torrents. Not a catchable exception, a crash. https://gist.github.com/gjedeer/afc60f32f241e5ea075fe862d1a11181 - this isn't necessarily related to skytorrents but looks like a bug in the frostwire library
- (so far) returns the torrent which downloaded from HTTP first instead of the one with most seeds. That's fixable of course.

Questions:
- How to handle more than one Torrent search engine? 
-- Search in parallel? 
-- Fall back when TPB fails to find meaningful results?

**Comment by funkyg** [comment]
Awesome, i didnt even know that site!

Looks like that site also has votes and verified torrents. So if quality is a problem, we could limit the search only to verified torrents, and/or torrents with a minimum number of upvotes.

From a quick look, it seems that skytorrents has better torrents than pirate bay (especially with faster downloads). So maybe we can just remove pirate bay completely and use only skytorrents. 

I see you already reported the libtorrent crash, so we will have to wait for that fix. Agree that it doesnt seem related to skytorrents, so nothing we can do really.
